### ISSUE TITLE
Weird timeout behaviour

### ISSUE THREAD

**Issue by S0urC10ud** [king/king-http-client#13]
Brief description:
After "connecting" to the BackEnd the idle-timeout seems to cause the connection to crash - which should probably not happen. I have also tried to set the idleTimeoutMills and totalRequestTimeoutMills to higher values like 10000 ms - same issue.

Reproducability:

Version 3.0.18
Code:
~~~~
SseClient sseClient= httpClient.createSSE("https://datagate.dev:6040/api/v1/events")
                .addHeader("Authorization", "Bearer " + APIConnection.token)
                .build()
                .execute(new SseClientCallback() {
            @Override
            public void onConnect() {
                logger.info("Connected to the SSE-Backend!");
            }

            @Override
            public void onDisconnect() {
                logger.info("Disconnected from the SSE-Backend!");
            }

            @Override
            public void onError(Throwable throwable) {
                logger.error("SSE-Error: " + throwable.toString());
                throwable.printStackTrace();
            }
}
~~~~
Error:
23:26:18.908 [HttpClient-HttpCallback 2] INFO  d.d.api.rest.sse.EventHandler - Connected to the SSE-Backend!
23:26:19.986 [HttpClient-HttpCallback 1] ERROR d.d.api.rest.sse.EventHandler - SSE-Error: com.king.platform.net.http.netty.TimeoutException: Idle timeout of 1000 ms was 1077 ms since last event
com.king.platform.net.http.netty.TimeoutException: Idle timeout of 1000 ms was 1077 ms since last event
	at com.king.platform.net.http.netty.IdleTimeoutTimerTask.run(IdleTimeoutTimerTask.java:66)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485)
	at java.lang.Thread.run(Thread.java:748)

**Comment by magnus-gustafsson** [comment]
Hey, 
I'm unable to reproduce this issue in an test case.
https://github.com/king/king-http-client/blob/master/integration-tests/src/test/java/com/king/platform/net/http/integration/HttpSse.java#L589

How are you specifying idleTimeoutMillis for the sse connection?

**Comment by S0urC10ud** [comment]
Hey there,

I just found out that a nginx reverse proxy was buffering the traffic. Thus, the keep-alive packets were delayed and the error was thrown - I'm really sorry...


You may of course delete the issue now
