### ISSUE TITLE
Follow relative redirects fails

### ISSUE THREAD

**Issue by jazcarate** [king/king-http-client#25]
When handling a redirect response that has a relative location,

https://github.com/king/king-http-client/blob/c34e14b36cc2c7250b10c209d8805d6098fa654f/client/src/main/java/com/king/platform/net/http/netty/response/HttpClientResponseHandler.java#L89

we try to build the new URL with `ServerInfo.buildFromUri`
https://github.com/king/king-http-client/blob/c34e14b36cc2c7250b10c209d8805d6098fa654f/client/src/main/java/com/king/platform/net/http/netty/response/HttpRedirector.java#L53

which fails with a relative location (e.x.: `/foo`)
https://github.com/king/king-http-client/blob/c34e14b36cc2c7250b10c209d8805d6098fa654f/client/src/main/java/com/king/platform/net/http/netty/ServerInfo.java#L79

We should either: Have a better error that relative URIs are not supported to follow redirects, or make the redirect enrich the URI with the absolute part of the `HttpRequestContext`

**Comment by magnus-gustafsson** [comment]
Yea, correct, it should support relative paths, not just absolute.

**Comment by magnus-gustafsson** [comment]
Fixed! 
Need to fix a issue with java17 before a new version is released.
